'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4927
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------



Partial Public Class UserForms_AppointmentDragToolTip

    ''' <summary>
    ''' lblInterval control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected lblInterval As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    ''' <summary>
    ''' lblInfo control.
    ''' </summary>
    ''' <remarks>
    ''' Auto-generated field.
    ''' To modify move field declaration from designer file to code-behind file.
    ''' </remarks>
    Protected lblInfo As Global.DevExpress.Web.ASPxEditors.ASPxLabel
End Class
